# Generated by Django 5.2.4 on 2026-05-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('new_users', models.IntegerField()),
                ('active_patients', models.IntegerField()),
                ('total_revenue', models.FloatField()),
                ('feedback_summary', models.TextField(blank=True)),
            ],
        ),
    ]
