# Generated by Django 5.2.4 on 2026-05-11 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(help_text="e.g., 'Day 1', 'Day 8', etc.", max_length=15)),
                ('feedback', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='User rating from 1 to 5.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DietRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_week_starting', models.DateField(default=django.utils.timezone.now)),
                ('meals', models.JSONField(default=dict, help_text='The full 15-day meal plan generated by AI.')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('nutritionist_comment', models.TextField(blank=True, help_text='Comments from the nutritionist for the user.', null=True)),
                ('user_profile_snapshot', models.JSONField(blank=True, help_text="Immutable JSON of the user's health vector at generation time.", null=True)),
                ('original_ai_plan', models.JSONField(blank=True, help_text='The unmodified plan from the AI for comparison.', null=True)),
                ('approved_for_retraining', models.BooleanField(default=False, help_text='Flagged by a nutritionist as a high-quality example for retraining.')),
                ('nutritionist_retraining_notes', models.TextField(blank=True, help_text="Internal notes for the ML team about this plan's quality.", null=True)),
                ('was_used_for_retraining', models.BooleanField(db_index=True, default=False, help_text='Set automatically after the plan is used for training.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='If true, this plan is treated as deleted and will be shown in the archive.')),
            ],
        ),
    ]
