# Generated by Django 5.2.4 on 2026-05-11 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dietfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dietrecommendation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_diets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dietrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dietfeedback',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='diet.dietrecommendation'),
        ),
        migrations.AlterUniqueTogether(
            name='dietfeedback',
            unique_together={('recommendation', 'user', 'day')},
        ),
    ]
