# Generated by Django 5.2.4 on 2026-06-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userFood", "0003_food_attributes_system"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="fooditemattribute",
            name="userFood_fo_food_item_idx",
        ),
        migrations.RemoveIndex(
            model_name="fooditemattribute",
            name="userFood_fo_attribut_idx",
        ),
        migrations.RemoveIndex(
            model_name="usermealattribute",
            name="userFood_us_user_mea_idx",
        ),
        migrations.RemoveIndex(
            model_name="usermealattribute",
            name="userFood_us_attribut_idx",
        ),
        migrations.AlterField(
            model_name="foodattribute",
            name="description",
            field=models.TextField(
                blank=True, help_text="What this attribute represents", null=True
            ),
        ),
        migrations.AlterField(
            model_name="foodattribute",
            name="name",
            field=models.CharField(
                help_text="e.g., 'Flour Type', 'Fat Type', 'Size'",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="foodattributeoption",
            name="value",
            field=models.CharField(
                help_text="The option value (e.g., 'Wheat', 'Toned')", max_length=100
            ),
        ),
    ]
