# Generated by Django 5.2.4 on 2026-05-11 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutritionist_type', models.CharField(choices=[('inhouse', 'In-house'), ('expert', 'Expert')], default='inhouse', max_length=20)),
                ('is_virtual_enabled', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PatientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateField(default=django.utils.timezone.now, help_text='The date the patient was officially assigned. Defaults to today, but can be changed.', verbose_name='Assignment Date')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
