# Generated by Django 5.2.4 on 2026-09-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionist', '0003_nutritionistprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionistprofile',
            name='is_offline_available',
            field=models.BooleanField(default=False, verbose_name='Available for Offline Appointment'),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='is_online_available',
            field=models.BooleanField(default=True, verbose_name='Available for Online Appointment'),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='offline_location',
            field=models.TextField(blank=True, help_text='Clinic/Practice address for offline appointments', null=True),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='offline_payment_required',
            field=models.BooleanField(default=True, help_text='Require payment upfront for offline appointments (True=Pay online, False=Pay at clinic/cash)'),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='offline_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current approved offline appointment price', max_digits=10),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='online_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current approved online appointment price', max_digits=10),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='pending_offline_payment_required',
            field=models.BooleanField(blank=True, help_text='Pending offline payment requirement setting', null=True),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='pending_offline_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pending requested offline price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='pending_online_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pending requested online price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='price_approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending Approval'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='price_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
