# Generated by Django 5.2.4 on 2026-09-16 08:27

import utils.cloud
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionist', '0004_nutritionistprofile_is_offline_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionistprofile',
            name='additional_certifications',
            field=models.FileField(blank=True, null=True, storage=utils.cloud.CustomCloudinaryStorage(), upload_to='nutritionist/certificates/'),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='current_organization',
            field=models.CharField(blank=True, help_text='Current clinic/hospital/organization name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='experience_certificate',
            field=models.FileField(blank=True, null=True, storage=utils.cloud.CustomCloudinaryStorage(), upload_to='nutritionist/certificates/'),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='government_id',
            field=models.FileField(blank=True, null=True, storage=utils.cloud.CustomCloudinaryStorage(), upload_to='nutritionist/documents/'),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='issuing_authority',
            field=models.CharField(blank=True, help_text='Relevant professional body', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='languages_spoken',
            field=models.JSONField(blank=True, default=list, help_text='List of languages spoken'),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='professional_bio',
            field=models.TextField(blank=True, help_text='Short introduction', null=True),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='professional_title',
            field=models.CharField(blank=True, help_text='e.g. Clinical Nutritionist / Dietitian', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, storage=utils.cloud.CustomCloudinaryStorage(), upload_to='nutritionist/photos/'),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='qualification',
            field=models.CharField(blank=True, help_text='e.g. MSc Nutrition & Dietetics', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='qualification_certificate',
            field=models.FileField(blank=True, null=True, storage=utils.cloud.CustomCloudinaryStorage(), upload_to='nutritionist/certificates/'),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, storage=utils.cloud.CustomCloudinaryStorage(), upload_to='nutritionist/certificates/'),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='registration_number',
            field=models.CharField(blank=True, help_text='NIN/State Registration No.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='specializations',
            field=models.JSONField(blank=True, default=list, help_text='List of specializations selected'),
        ),
        migrations.AddField(
            model_name='nutritionistprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Years of professional practice', null=True),
        ),
    ]
