# Generated by Django 5.2.4 on 2026-05-11 12:03

import django.db.models.deletion
import django.utils.timezone
import utils.cloud
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.now, help_text='The date the lab report was generated.')),
                ('report_file', models.FileField(blank=True, help_text='Upload your lab report PDF, scanned reports, or documents', null=True, storage=utils.cloud.CustomCloudinaryStorage(), upload_to='reports/files/')),
                ('weight_kg', models.FloatField(blank=True, help_text='Weight in kg at the time of the report.', null=True)),
                ('height_cm', models.FloatField(blank=True, help_text='Height in cm at the time of the report.', null=True)),
                ('waist_circumference_cm', models.FloatField(blank=True, help_text='Waist circumference in cm.', null=True)),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('fasting_blood_sugar', models.FloatField(blank=True, help_text='mg/dL', null=True)),
                ('postprandial_sugar', models.FloatField(blank=True, help_text='mg/dL', null=True)),
                ('hba1c', models.FloatField(blank=True, help_text='%', null=True)),
                ('ldl_cholesterol', models.FloatField(blank=True, help_text='mg/dL', null=True)),
                ('hdl_cholesterol', models.FloatField(blank=True, help_text='mg/dL', null=True)),
                ('triglycerides', models.FloatField(blank=True, help_text='mg/dL', null=True)),
                ('crp', models.FloatField(blank=True, help_text='mg/L', null=True)),
                ('esr', models.FloatField(blank=True, help_text='mm/hr', null=True)),
                ('uric_acid', models.FloatField(blank=True, help_text='mg/dL', null=True)),
                ('creatinine', models.FloatField(blank=True, help_text='mg/dL', null=True)),
                ('urea', models.FloatField(blank=True, help_text='mg/dL', null=True)),
                ('alt', models.FloatField(blank=True, help_text='U/L', null=True)),
                ('ast', models.FloatField(blank=True, help_text='U/L', null=True)),
                ('vitamin_d3', models.FloatField(blank=True, help_text='ng/mL', null=True)),
                ('vitamin_b12', models.FloatField(blank=True, help_text='pg/mL', null=True)),
                ('tsh', models.FloatField(blank=True, help_text='µIU/mL', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('occupation', models.CharField(blank=True, help_text='e.g., Software Developer, Teacher, Construction Worker', max_length=100)),
                ('height_cm', models.FloatField(blank=True, help_text="User's current height in cm", null=True)),
                ('weight_kg', models.FloatField(blank=True, help_text="User's current weight in kg", null=True)),
                ('activity_level', models.CharField(blank=True, choices=[('Sedentary', 'Sedentary (little or no exercise)'), ('Lightly Active', 'Lightly Active (light exercise/sports 1-3 days/week)'), ('Moderately Active', 'Moderately Active (moderate exercise/sports 3-5 days/week)'), ('Very Active', 'Very Active (hard exercise/sports 6-7 days a week)'), ('Extra Active', 'Extra Active (very hard exercise/physical job)')], max_length=50, null=True)),
                ('goal', models.CharField(blank=True, choices=[('Lose Weight', 'Lose Weight'), ('Maintain Weight', 'Maintain Weight'), ('Gain Weight', 'Gain Weight')], max_length=20, null=True)),
                ('diet_type', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non Vegetarian', 'Non Vegetarian'), ('Vegan', 'Vegan'), ('Eggetarian', 'Eggetarian'), ('Keto', 'Keto'), ('Other', 'Other')], default='other', max_length=20)),
                ('allergies', models.TextField(blank=True, help_text='List known food allergies, separated by commas.')),
                ('is_diabetic', models.BooleanField(default=False, verbose_name='Known Diabetic Condition')),
                ('is_hypertensive', models.BooleanField(default=False, verbose_name='Known Hypertension (High BP)')),
                ('has_heart_condition', models.BooleanField(default=False, verbose_name='Known Heart Condition (CVD)')),
                ('has_thyroid_disorder', models.BooleanField(default=False, verbose_name='Known Thyroid Disorder')),
                ('has_arthritis', models.BooleanField(default=False, verbose_name='Known Arthritis (RA/OA/Gout)')),
                ('has_gastric_issues', models.BooleanField(default=False, verbose_name='Known Gastric Issues (IBS/GERD)')),
                ('other_chronic_condition', models.TextField(blank=True, help_text='Describe any other long-term health conditions.')),
                ('family_history', models.TextField(blank=True, help_text='Describe significant family history of diseases.')),
                ('is_pregnant', models.BooleanField(default=False, verbose_name='Currently Pregnant')),
                ('due_date', models.DateField(blank=True, help_text='The estimated due date, if pregnant.', null=True)),
                ('is_breastfeeding', models.BooleanField(default=False, verbose_name='Currently Breastfeeding')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
