# Generated by Django 5.2.4 on 2026-05-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_category', models.CharField(choices=[('IN_HOUSE', 'In House'), ('EXPERT', 'Expert')], db_index=True, max_length=20)),
                ('appointment_type', models.CharField(choices=[('IN_PERSON', 'In Person'), ('VIRTUAL', 'Virtual')], max_length=20)),
                ('assigned_by', models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User'), ('ADMIN', 'Admin')], max_length=10)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], db_index=True, default='CONFIRMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PATIENT', 'Patient'), ('NUTRITIONIST', 'Nutritionist')], max_length=20)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_at', models.DateTimeField(db_index=True)),
                ('reminder_type', models.CharField(choices=[('24H', '24 Hours'), ('2H', '2 Hours')], max_length=5)),
                ('is_sent', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
