# Generated by Django 5.2.4 on 2026-05-11 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='nutritionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutritionist_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='selected_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_selected_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentfeedback',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentfeedback',
            name='given_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_reminders', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='nutritionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='appointments.availabilityslot'),
        ),
        migrations.AlterUniqueTogether(
            name='appointmentfeedback',
            unique_together={('appointment', 'given_by')},
        ),
        migrations.AddIndex(
            model_name='appointmentreminder',
            index=models.Index(fields=['is_sent', 'remind_at'], name='appointment_is_sent_cc36da_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['nutritionist', 'is_booked'], name='appointment_nutriti_f0db6e_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['nutritionist', '-date', '-start_time'], name='appointment_nutriti_3ee1cd_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['nutritionist', 'date'], name='appointment_nutriti_033999_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['nutritionist', 'status'], name='appointment_nutriti_667e32_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'created_at'], name='appointment_patient_f2c3c0_idx'),
        ),
    ]
