# Generated by Django 5.2.4 on 2026-09-09 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslot',
            name='slot_type',
            field=models.CharField(choices=[('VIRTUAL', 'Virtual'), ('IN_PERSON', 'In-Clinic'), ('BOTH', 'Both (Virtual & In-Clinic)')], db_index=True, default='BOTH', max_length=20),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['nutritionist', 'slot_type'], name='appointment_nutriti_693312_idx'),
        ),
    ]
