# Generated by Django 5.2.4 on 2026-09-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_create_appointmentfeedback_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
