# Generated by Django 5.2.4 on 2026-09-26 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_instructions_appointment_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('PATIENT', 'Patient'), ('NUTRITIONIST', 'Nutritionist'), ('ADMIN', 'Admin')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Consultation fee received by platform', max_digits=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid / Pay at Clinic'), ('PAID', 'Paid Online'), ('PENDING_REFUND', 'Pending Refund'), ('REFUNDED', 'Refunded'), ('NO_REFUND', 'No Refund Applicable')], db_index=True, default='UNPAID', max_length=25),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payout_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Net payout owed/transferred to nutritionist', max_digits=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payout_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payout_status',
            field=models.CharField(choices=[('PENDING', 'Pending Admin Payout'), ('PAID', 'Paid Out to Nutritionist'), ('CANCELLED', 'Cancelled (No Payout)'), ('NOT_APPLICABLE', 'Not Applicable')], db_index=True, default='NOT_APPLICABLE', max_length=25),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payout_transaction_ref',
            field=models.CharField(blank=True, default='', help_text='Admin transaction reference for payout disbursement', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount to be refunded to patient if eligible', max_digits=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='refund_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.availabilityslot'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['payment_status', 'payout_status'], name='appointment_payment_427edd_idx'),
        ),
    ]
