# Generated by Django 5.2.4 on 2026-05-11 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pending_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('duration_days', models.PositiveIntegerField()),
                ('plan_type', models.CharField(choices=[('patient', 'Patient'), ('nutritionist', 'Nutritionist')], default='patient', max_length=20)),
                ('weight_tracker_allowed', models.BooleanField(default=False)),
                ('nutrition_search_allowed', models.BooleanField(default=False)),
                ('custom_reminder_allowed', models.BooleanField(default=False)),
                ('chat_allowed', models.BooleanField(default=False)),
                ('appointment_allowed', models.BooleanField(default=False)),
                ('ai_diet_allowed', models.BooleanField(default=False)),
                ('BMI_Calculator_allowed', models.BooleanField(default=False)),
                ('Fat_Calculator_allowed', models.BooleanField(default=False)),
                ('expert_consults', models.PositiveIntegerField(default=0)),
                ('inhouse_consults', models.PositiveIntegerField(default=0)),
                ('meal_log_allowed', models.BooleanField(default=False)),
                ('water_intake_allowed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('inhouse_consultation_fee', models.PositiveIntegerField(default=200, help_text='Fee in rupees for single inhouse consultation')),
                ('expert_consultation_fee', models.PositiveIntegerField(default=500, help_text='Fee in rupees for single expert consultation')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('remaining_expert', models.PositiveIntegerField(default=0)),
                ('remaining_inhouse', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
