# Generated by Django 5.2.4 on 2026-09-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='nutri_ai_diet_allowed',
            field=models.BooleanField(default=True, help_text='Allows AI-powered automated diet formulations for patients', verbose_name='AI Assistant / Smart AI Diet Formulation'),
        ),
        migrations.AddField(
            model_name='plan',
            name='nutri_bulk_upload_allowed',
            field=models.BooleanField(default=False, help_text='Allows batch importing patients via CSV/Excel template', verbose_name='Bulk Patient Upload (CSV/Excel)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='nutri_chat_allowed',
            field=models.BooleanField(default=True, help_text='Allows direct real-time chat with assigned patients', verbose_name='Direct Real-time Patient Messaging'),
        ),
        migrations.AddField(
            model_name='plan',
            name='nutri_export_reports_allowed',
            field=models.BooleanField(default=False, help_text='Allows generating PDF reports and advanced clinical analytics', verbose_name='Diet Chart PDF Export & Advanced Analytics'),
        ),
        migrations.AddField(
            model_name='plan',
            name='nutri_lab_reports_allowed',
            field=models.BooleanField(default=True, help_text='Allows uploading and analyzing patient lab tests and health reports', verbose_name='Lab Report Uploads & Biomarker Tracking'),
        ),
        migrations.AddField(
            model_name='plan',
            name='nutri_manual_diet_allowed',
            field=models.BooleanField(default=True, help_text='Allows custom manual diet plan formulation & template editing', verbose_name='Manual Diet Formulation & Editing'),
        ),
        migrations.AddField(
            model_name='plan',
            name='nutri_max_patients',
            field=models.PositiveIntegerField(default=25, help_text='Maximum number of active assigned patients allowed (0 = Unlimited)', verbose_name='Max Active Patients Capacity'),
        ),
        migrations.AddField(
            model_name='plan',
            name='nutri_offline_appointment_allowed',
            field=models.BooleanField(default=True, help_text='Allows in-person clinic appointments and scheduling', verbose_name='Offline Clinic Appointments'),
        ),
        migrations.AddField(
            model_name='plan',
            name='nutri_online_appointment_allowed',
            field=models.BooleanField(default=True, help_text='Allows offering and accepting virtual video consultation appointments', verbose_name='Online Video Appointments'),
        ),
        migrations.AddField(
            model_name='plan',
            name='nutri_smart_assistant_allowed',
            field=models.BooleanField(default=True, help_text='Allows access to Nutro Smart Calorie Assistant', verbose_name='Smart Assistant (Nutro AI Calorie & Nutrition)'),
        ),
    ]
