# Generated by Django 5.2.4 on 2026-10-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_plan_nutri_ai_diet_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, default='subscription', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='expert_consults',
            field=models.PositiveIntegerField(default=0, help_text='Number of expert consultations included (0 = Unlimited)', verbose_name='Expert Consultations Count'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='inhouse_consults',
            field=models.PositiveIntegerField(default=0, help_text='Number of in-house consultations included (0 = Unlimited)', verbose_name='In-House Consultations Count'),
        ),
    ]
